### ISSUE TITLE
Call to undefined function ContaoCommunityAlliance\Contao\Composer\Controller\posix_kill()

### ISSUE THREAD

**Issue by fritzmg** [contao-community-alliance/composer-client#276] opened 2016-01-27 09:25 UTC
On some systems I get the following error, when running composer in `detached` mode as soon as I start the test run or update:
```
Fatal error: Call to undefined function ContaoCommunityAlliance\Contao\Composer\Controller\posix_kill() in …/system/modules/!composer/src/Controller/DetachedController.php on line 45
```
This error message will persist as long as the `/system/tmp/composer.pid` is present. To access the package management section of Contao, I have to delete that file manually.

This happens on my local system (Windows 7 x64, PHP 5.5, XAMPP, PHP under CGI) as well as on another Server (CentOS 6.4, PHP 5.6.17, PHP is running as an Apache Module).

**Comment by discordier** [comment] 2016-01-27 22:27
What Version of PHP do you have?
That function is activated by default for ages.

**Comment by fritzmg** [comment] 2016-01-28 06:34
I already posted the PHP version ;)

**Comment by Toflar** [comment] 2016-01-28 07:45
You can compile it without posix though. Can you check if posix was deactivated?

**Comment by fritzmg** [comment] 2016-01-28 07:53
You are right, in case of CentOS' PHP 5.6 version, you have to install `php56w-process` as well, which includes `php-posix` among other things.

Under XAMPP I am not sure, it does not come with a `php_process.dll` or `php_posix.dll` by default.

**Comment by fritzmg** [comment] 2016-01-28 08:01
Yes, php.posix is not available under Windows: http://de.php.net/manual/en/intro.posix.php

This is a shame, now the `detached` mode is cumbersome to use under Windows. The process runs just fine, however due to the usage of posix, I cannot access the package management in the Contao backend, as long as the `/system/tmp/composer.pid` is present.

**Comment by discordier** [comment] 2016-01-28 09:29
Will have to do so... :(
When will Windows finally become a full fledged OS? *sigh*

**Comment by discordier** [comment] 2016-01-28 09:30
On a side note, how come Windows has a kill utility? Does it really work?

**Comment by fritzmg** [comment] 2016-01-28 09:30
I guess not.

**Comment by fritzmg** [comment] 2016-01-28 09:32
Under Windows (Windows 7 and up at least) it's `taskkill`, e.g. `taskkill /PID 1234`

**Comment by discordier** [comment] 2016-01-28 15:58
@fritzmg, could you please test the following function as replacement in Windows?
If it works, I'll implement it.
```php
<?php 
function win_kill($pid){
    $wmi   = new COM("winmgmts:{impersonationLevel=impersonate}!\\\\.\\root\\cimv2");
    $procs = $wmi->ExecQuery("SELECT * FROM Win32_Process WHERE ProcessId='" . $pid . "'");
    $proc  = reset($procs)
    $proc->Terminate();
?>
```

**Comment by fritzmg** [comment] 2016-01-28 18:23
`COM` requires the [COM](http://php.net/manual/en/class.com.php) PHP extension - which I do not seem to have (there is no `php_com_dotnet.dll` bundled with my XAMPP installation at least).

I tried
```php
shell_exec(sprintf('taskkill /PID %d', $pid));
```
though which worked fine.

**Comment by discordier** [comment] 2016-01-28 19:50
Which now depends on `shell_exec` in addition to `proc_open`.

I'm not happy with this change, but hey, it should work most times.

We will need an additional check if the function is disabled though.

**Comment by discordier** [comment] 2016-02-02 16:15
We need to replace the check on [this line](https://github.com/contao-community-alliance/composer-client/blob/a1c77eb41528f8608b7a2080c084fa6ec252ad3f/src/system/modules/!composer/src/Controller/DetachedController.php#L45) as well but I did not find any elegant windows solution yet:
```php
// We send special signal 0 to test for existance of the process which is much more bullet proof than
// using anything like shell_exec() wrapped ps/pgrep magic (which is not available on all systems).
$isRunning = (bool) posix_kill($pid, 0);
```
@fritzmg any suggestions?

**Comment by fritzmg** [comment] 2016-02-02 16:29
Hm... I don't know, I can only tell you what task kill returns:
```
>TASKKILL /PID 1234
ERROR: The process "1234" not found.

>TASKKILL /PID 1234
SUCCESS: Sent termination signal to the process with PID 1234.
```

**Comment by discordier** [comment] 2016-02-02 18:00
The problem is, I do not want to kill the process but check if it is still running and then enable the button to kill it.

**Comment by backbone87** [comment] 2016-02-02 18:50
`in_array($pid, str_getcsv(shell_exec(sprintf('tasklist /FI "PID eq %s" /FO CSV /NH', $pid))))`

**Comment by discordier** [comment] 2016-02-02 19:56
Please test with b0f8fcd in the hotfix branch so we can release asap.

**Comment by backbone87** [comment] 2016-02-03 06:49
@discordier i commented on the commit for few cleanups
@fritzmg can you please test the hotfix, once @discordier cleaned up the commit?

**Comment by fritzmg** [comment] 2016-02-03 08:45
Sure :)

**Comment by discordier** [comment] 2016-02-04 19:25
@backbone87 See my replies in the commit, the naming has been fixed in c038693d3d6108def1c165b57ec4c0cf3b174734

**Comment by fritzmg** [comment] 2016-02-04 20:03
Hm, I am not quite sure this is working as intended. When I click "Update Packages" it seems as though composer is running in `inline` mode, even though I defined the `detached` mode. I only see the console output after composer finished (however I see the console window as if it was running in `detached` mode).

**Comment by discordier** [comment] 2016-02-04 20:18
In these cases, you should see a clear warning in the like of:
`<function name> is disabled, reverting from detached to inline execution`
Where `<function name>` is the name of a function not available on your installation.

**Comment by fritzmg** [comment] 2016-02-05 09:04
What I mean is: before `0.15.2` (and under Linux) I can see the console output while the process is still running (with the green bar going from left to right). Currently this does not seem to be the case.

**Comment by fritzmg** [comment] 2016-02-05 12:53
Also, there is no `/system/tmp/composer.pid` file created during the package update process.

**Comment by discordier** [comment] 2016-02-09 12:33
@fritzmg There are two reasons for which the composer may run in inline mode.
1. You configured it to do so (easy one).
2. The self test within our client came to the conclusion that running detached is not possible on your system and therefore reverts from detached to inline mode. If this should be the case, it will inform you about this with an warning message.

**Comment by fritzmg** [comment] 2016-02-09 12:41
> 2. The self test within our client came to the conclusion that running detached is not possible on your system and therefore reverts from detached to inline mode. If this should be the case, it will inform you about this with a warning message.

But it does not inform me with a warning message. I'll explain what happens again:

* I click on "Update Packages"
* This client request runs as long as the composer update in the background takes - which indicates that is running in `inline` mode
* During this process, no `composer.pid` files i created under `system/tmp` - which also indicates that the composer update is running in `inline` mode
* After it is finished, I see the console ouptut of composer, as if it was running in `detached` mode
* At no point do I see a warning, that the the composer-client is reverting from detached to inline mode

**Comment by discordier** [comment] 2016-02-09 21:09
This is an indicator that composer runs within the same process.
Can you please check the configuration again and post the relevant lines from localconfig?

**Comment by fritzmg** [comment] 2016-02-10 09:04
`localconfig.php`:
```php
$GLOBALS['TL_CONFIG']['composerExecutionMode'] = 'detached';
$GLOBALS['TL_CONFIG']['composerPhpPath'] = 'php -d memory_limit=1G -d max_execution_time=900';
```
When I put `echo $mode; exit;` right after `$mode = $this->determineRuntimeMode();` I get `detached`.

Example console output (where nothing needs to be updated):
```
$ php -d memory_limit=1G -d max_execution_time=900 composer.phar update --no-ansi --no-interaction
Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
```

From debugging I can see that
```
$processId = shell_exec($cmd);
```
blocks, until composer is finished. That's why no `composer.pid` file is created, since that would happen immediately afterwards.

However, as far as I can see, nothing has changed here since `0.15.1`.

**Closed** 2016-02-18 19:58 UTC
Labels: bug, need-windows, testing
