### ISSUE TITLE
If a search for "metamodels" don't return all results [0.15.2]

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [contao-community-alliance/composer-client#256] opened 2015-07-24 08:53 UTC
If a search for "metamodels" don't return all results. If I search for "attribute_checkbox", the "metamodels/attribute_checkbox" is showed as result. "attribute_checkbox" is only one example.
The keyword metamodels is given in the composer.json and the attribute is kompatible.

**Comment by fritzmg** [comment] 2016-02-03 08:46
Duplicate of #244

**Closed** 2016-02-09 12:33 UTC
Labels: duplicate
